#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : nvidia
Version  : 460.56
Release  : 9
URL      : file:///aot/build/clearlinux/packages/nvidia/nvidia-460.56.tar.gz
Source0  : file:///aot/build/clearlinux/packages/nvidia/nvidia-460.56.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: nvidia-bin = %{version}-%{release}
Requires: nvidia-data = %{version}-%{release}
Requires: nvidia-lib = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : findutils
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
# Ignore missing build ids
%undefine _missing_build_ids_terminate_build
# Disable automatic requeriments processing
AutoReq: no

%description
No detailed description available

%package bin
Summary: bin components for the nvidia package.
Group: Binaries
Requires: nvidia-data = %{version}-%{release}
# Disable automatic requeriments processing
AutoReq: no

%description bin
bin components for the nvidia package.


%package data
Summary: data components for the nvidia package.
Group: Data
# Disable automatic requeriments processing
AutoReq: no

%description data
data components for the nvidia package.


%package dev
Summary: dev components for the nvidia package.
Group: Development
Requires: nvidia-lib = %{version}-%{release}
Requires: nvidia-bin = %{version}-%{release}
Requires: nvidia-data = %{version}-%{release}
Provides: nvidia-devel = %{version}-%{release}
Requires: nvidia = %{version}-%{release}
# Disable automatic requeriments processing
AutoReq: no

%description dev
dev components for the nvidia package.


%package dev32
Summary: dev32 components for the nvidia package.
Group: Default
Requires: nvidia-lib32 = %{version}-%{release}
Requires: nvidia-bin = %{version}-%{release}
Requires: nvidia-data = %{version}-%{release}
Requires: nvidia-dev = %{version}-%{release}
# Disable automatic requeriments processing
AutoReq: no

%description dev32
dev32 components for the nvidia package.


%package lib
Summary: lib components for the nvidia package.
Group: Libraries
Requires: nvidia-data = %{version}-%{release}
# Disable automatic requeriments processing
AutoReq: no

%description lib
lib components for the nvidia package.


%package lib32
Summary: lib32 components for the nvidia package.
Group: Default
Requires: nvidia-data = %{version}-%{release}
# Disable automatic requeriments processing
AutoReq: no

%description lib32
lib32 components for the nvidia package.


%prep
%setup -q -c -n nvidia-460.56.tar
cd %{_builddir}/nvidia-460.56.tar

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1615758251
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="-O3 -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -Wno-error -Wp,-D_REENTRANT -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -feliminate-unused-debug-types -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=12 -fno-PIC -fno-PIE -fno-math-errno -fno-pie -fno-plt -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -g -m64 -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native -pipe "
export FCFLAGS="-O3 -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -Wno-error -Wp,-D_REENTRANT -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -feliminate-unused-debug-types -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=12 -fno-PIC -fno-PIE -fno-math-errno -fno-pie -fno-plt -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -g -m64 -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native -pipe "
export FFLAGS="-O3 -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -Wno-error -Wp,-D_REENTRANT -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -feliminate-unused-debug-types -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=12 -fno-PIC -fno-PIE -fno-math-errno -fno-pie -fno-plt -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -g -m64 -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native -pipe "
export CFFLAGS="-O3 -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -Wno-error -Wp,-D_REENTRANT -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -feliminate-unused-debug-types -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=12 -fno-PIC -fno-PIE -fno-math-errno -fno-pie -fno-plt -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -g -m64 -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native -pipe "
export LDFLAGS="-O3 -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=12 -fno-PIC -fno-PIE -fno-pie -fno-plt -fno-semantic-interposition -fno-stack-protector -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native "
export CXXFLAGS="-O3 -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-sort-common -Wl,-z,now -Wl,-z,relro -Wno-error -Wp,-D_REENTRANT -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -feliminate-unused-debug-types -ffat-lto-objects -fipa-pta -floop-nest-optimize -flto=12 -fno-PIC -fno-PIE -fno-math-errno -fno-pie -fno-plt -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -fpic -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -fvisibility-inlines-hidden -g -m64 -malign-data=cacheline -march=native -mtls-dialect=gnu2 -mtune=native -pipe "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1615758251
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/nvidia/bin/nvidia-bug-report.sh
/usr/nvidia/bin/nvidia-cuda-mps-control
/usr/nvidia/bin/nvidia-cuda-mps-server
/usr/nvidia/bin/nvidia-debugdump
/usr/nvidia/bin/nvidia-installer
/usr/nvidia/bin/nvidia-ngx-updater
/usr/nvidia/bin/nvidia-persistenced
/usr/nvidia/bin/nvidia-settings
/usr/nvidia/bin/nvidia-smi
/usr/nvidia/bin/nvidia-uninstall
/usr/nvidia/bin/nvidia-xconfig

%files data
%defattr(-,root,root,-)
/usr/nvidia/share/applications/nvidia-settings.desktop

%files dev
%defattr(-,root,root,-)
/usr/nvidia/lib64/libEGL.so
/usr/nvidia/lib64/libGL.so
/usr/nvidia/lib64/libGLESv1_CM.so
/usr/nvidia/lib64/libGLESv2.so
/usr/nvidia/lib64/libGLX.so
/usr/nvidia/lib64/libOpenCL.so
/usr/nvidia/lib64/libOpenGL.so
/usr/nvidia/lib64/libcuda.so
/usr/nvidia/lib64/libnvcuvid.so
/usr/nvidia/lib64/libnvidia-allocator.so
/usr/nvidia/lib64/libnvidia-cfg.so
/usr/nvidia/lib64/libnvidia-encode.so
/usr/nvidia/lib64/libnvidia-fbc.so
/usr/nvidia/lib64/libnvidia-ifr.so
/usr/nvidia/lib64/libnvidia-ml.so
/usr/nvidia/lib64/libnvidia-opticalflow.so
/usr/nvidia/lib64/libnvidia-ptxjitcompiler.so
/usr/nvidia/lib64/libvdpau_nvidia.so

%files dev32
%defattr(-,root,root,-)
/usr/nvidia/lib32/libEGL.so
/usr/nvidia/lib32/libGL.so
/usr/nvidia/lib32/libGLESv1_CM.so
/usr/nvidia/lib32/libGLESv2.so
/usr/nvidia/lib32/libGLX.so
/usr/nvidia/lib32/libOpenCL.so
/usr/nvidia/lib32/libOpenGL.so
/usr/nvidia/lib32/libcuda.so
/usr/nvidia/lib32/libnvcuvid.so
/usr/nvidia/lib32/libnvidia-allocator.so
/usr/nvidia/lib32/libnvidia-encode.so
/usr/nvidia/lib32/libnvidia-fbc.so
/usr/nvidia/lib32/libnvidia-ifr.so
/usr/nvidia/lib32/libnvidia-ml.so
/usr/nvidia/lib32/libnvidia-opticalflow.so
/usr/nvidia/lib32/libnvidia-ptxjitcompiler.so
/usr/nvidia/lib32/libvdpau_nvidia.so

%files lib
%defattr(-,root,root,-)
/usr/nvidia/lib64/libEGL.so.1
/usr/nvidia/lib64/libEGL.so.1.1.0
/usr/nvidia/lib64/libEGL_nvidia.so.0
/usr/nvidia/lib64/libEGL_nvidia.so.460.56
/usr/nvidia/lib64/libGL.so.1
/usr/nvidia/lib64/libGL.so.1.7.0
/usr/nvidia/lib64/libGLESv1_CM.so.1
/usr/nvidia/lib64/libGLESv1_CM.so.1.2.0
/usr/nvidia/lib64/libGLESv1_CM_nvidia.so.1
/usr/nvidia/lib64/libGLESv1_CM_nvidia.so.460.56
/usr/nvidia/lib64/libGLESv2.so.2
/usr/nvidia/lib64/libGLESv2.so.2.1.0
/usr/nvidia/lib64/libGLESv2_nvidia.so.2
/usr/nvidia/lib64/libGLESv2_nvidia.so.460.56
/usr/nvidia/lib64/libGLX.so.0
/usr/nvidia/lib64/libGLX_indirect.so.0
/usr/nvidia/lib64/libGLX_nvidia.so.0
/usr/nvidia/lib64/libGLX_nvidia.so.460.56
/usr/nvidia/lib64/libGLdispatch.so.0
/usr/nvidia/lib64/libOpenCL.so.1
/usr/nvidia/lib64/libOpenCL.so.1.0
/usr/nvidia/lib64/libOpenCL.so.1.0.0
/usr/nvidia/lib64/libOpenGL.so.0
/usr/nvidia/lib64/libcuda.so.1
/usr/nvidia/lib64/libcuda.so.460.56
/usr/nvidia/lib64/libnvcuvid.so.1
/usr/nvidia/lib64/libnvcuvid.so.460.56
/usr/nvidia/lib64/libnvidia-allocator.so.1
/usr/nvidia/lib64/libnvidia-allocator.so.460.56
/usr/nvidia/lib64/libnvidia-cbl.so.460.56
/usr/nvidia/lib64/libnvidia-cfg.so.1
/usr/nvidia/lib64/libnvidia-cfg.so.460.56
/usr/nvidia/lib64/libnvidia-compiler.so.460.56
/usr/nvidia/lib64/libnvidia-egl-wayland.so.1
/usr/nvidia/lib64/libnvidia-egl-wayland.so.1.1.5
/usr/nvidia/lib64/libnvidia-eglcore.so.460.56
/usr/nvidia/lib64/libnvidia-encode.so.1
/usr/nvidia/lib64/libnvidia-encode.so.460.56
/usr/nvidia/lib64/libnvidia-fbc.so.1
/usr/nvidia/lib64/libnvidia-fbc.so.460.56
/usr/nvidia/lib64/libnvidia-glcore.so.460.56
/usr/nvidia/lib64/libnvidia-glsi.so.460.56
/usr/nvidia/lib64/libnvidia-glvkspirv.so.460.56
/usr/nvidia/lib64/libnvidia-gtk2.so.460.56
/usr/nvidia/lib64/libnvidia-gtk3.so.460.56
/usr/nvidia/lib64/libnvidia-ifr.so.1
/usr/nvidia/lib64/libnvidia-ifr.so.460.56
/usr/nvidia/lib64/libnvidia-ml.so.1
/usr/nvidia/lib64/libnvidia-ml.so.460.56
/usr/nvidia/lib64/libnvidia-ngx.so.1
/usr/nvidia/lib64/libnvidia-ngx.so.460.56
/usr/nvidia/lib64/libnvidia-opencl.so.1
/usr/nvidia/lib64/libnvidia-opencl.so.460.56
/usr/nvidia/lib64/libnvidia-opticalflow.so.1
/usr/nvidia/lib64/libnvidia-opticalflow.so.460.56
/usr/nvidia/lib64/libnvidia-ptxjitcompiler.so.1
/usr/nvidia/lib64/libnvidia-ptxjitcompiler.so.460.56
/usr/nvidia/lib64/libnvidia-rtcore.so.460.56
/usr/nvidia/lib64/libnvidia-tls.so.460.56
/usr/nvidia/lib64/libnvoptix.so.1
/usr/nvidia/lib64/libnvoptix.so.460.56
/usr/nvidia/lib64/vdpau/libvdpau_nvidia.so.1
/usr/nvidia/lib64/vdpau/libvdpau_nvidia.so.460.56
/usr/nvidia/lib64/xorg/modules/drivers/nvidia_drv.so
/usr/nvidia/lib64/xorg/modules/extensions/libglxserver_nvidia.so
/usr/nvidia/lib64/xorg/modules/extensions/libglxserver_nvidia.so.460.56

%files lib32
%defattr(-,root,root,-)
/usr/nvidia/lib32/libEGL.so.1
/usr/nvidia/lib32/libEGL.so.1.1.0
/usr/nvidia/lib32/libEGL_nvidia.so.0
/usr/nvidia/lib32/libEGL_nvidia.so.460.56
/usr/nvidia/lib32/libGL.so.1
/usr/nvidia/lib32/libGL.so.1.7.0
/usr/nvidia/lib32/libGLESv1_CM.so.1
/usr/nvidia/lib32/libGLESv1_CM.so.1.2.0
/usr/nvidia/lib32/libGLESv1_CM_nvidia.so.1
/usr/nvidia/lib32/libGLESv1_CM_nvidia.so.460.56
/usr/nvidia/lib32/libGLESv2.so.2
/usr/nvidia/lib32/libGLESv2.so.2.1.0
/usr/nvidia/lib32/libGLESv2_nvidia.so.2
/usr/nvidia/lib32/libGLESv2_nvidia.so.460.56
/usr/nvidia/lib32/libGLX.so.0
/usr/nvidia/lib32/libGLX_indirect.so.0
/usr/nvidia/lib32/libGLX_nvidia.so.0
/usr/nvidia/lib32/libGLX_nvidia.so.460.56
/usr/nvidia/lib32/libGLdispatch.so.0
/usr/nvidia/lib32/libOpenCL.so.1
/usr/nvidia/lib32/libOpenCL.so.1.0
/usr/nvidia/lib32/libOpenCL.so.1.0.0
/usr/nvidia/lib32/libOpenGL.so.0
/usr/nvidia/lib32/libcuda.so.1
/usr/nvidia/lib32/libcuda.so.460.56
/usr/nvidia/lib32/libnvcuvid.so.1
/usr/nvidia/lib32/libnvcuvid.so.460.56
/usr/nvidia/lib32/libnvidia-allocator.so.1
/usr/nvidia/lib32/libnvidia-allocator.so.460.56
/usr/nvidia/lib32/libnvidia-compiler.so.460.56
/usr/nvidia/lib32/libnvidia-eglcore.so.460.56
/usr/nvidia/lib32/libnvidia-encode.so.1
/usr/nvidia/lib32/libnvidia-encode.so.460.56
/usr/nvidia/lib32/libnvidia-fbc.so.1
/usr/nvidia/lib32/libnvidia-fbc.so.460.56
/usr/nvidia/lib32/libnvidia-glcore.so.460.56
/usr/nvidia/lib32/libnvidia-glsi.so.460.56
/usr/nvidia/lib32/libnvidia-glvkspirv.so.460.56
/usr/nvidia/lib32/libnvidia-ifr.so.1
/usr/nvidia/lib32/libnvidia-ifr.so.460.56
/usr/nvidia/lib32/libnvidia-ml.so.1
/usr/nvidia/lib32/libnvidia-ml.so.460.56
/usr/nvidia/lib32/libnvidia-opencl.so.1
/usr/nvidia/lib32/libnvidia-opencl.so.460.56
/usr/nvidia/lib32/libnvidia-opticalflow.so.1
/usr/nvidia/lib32/libnvidia-opticalflow.so.460.56
/usr/nvidia/lib32/libnvidia-ptxjitcompiler.so.1
/usr/nvidia/lib32/libnvidia-ptxjitcompiler.so.460.56
/usr/nvidia/lib32/libnvidia-tls.so.460.56
/usr/nvidia/lib32/vdpau/libvdpau_nvidia.so.1
/usr/nvidia/lib32/vdpau/libvdpau_nvidia.so.460.56
